using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UI;
using System.Collections;


[RequireComponent(typeof(CharacterController))]
public class PlayerControllerWithCamera : MonoBehaviour
{
    [Header("ï¿½Ú“ï¿½ï¿½Ì‘ï¿½ï¿½ï¿½"), SerializeField]
    private float _speed = 3;
    private float weapon_speed = 0.3f;
    
    [Header("run"), SerializeField]
    private float run_speed = 2f;

    [Header("damage"), SerializeField]
    private float damage_speed = 0.8f;

    [Header("ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½ï¿½uï¿½Ô‚Ì‘ï¿½ï¿½ï¿½"), SerializeField]
    private float _jumpSpeed = 7;

    [Header("ï¿½dï¿½Í‰ï¿½ï¿½ï¿½ï¿½x"), SerializeField]
    private float _gravity = 15;

    [Header("ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì‘ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½iInfinityï¿½Å–ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½j"), SerializeField]
    private float _fallSpeed = 10;

    [Header("ï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½"), SerializeField]
    private float _initFallSpeed = 2;

    [Header("ï¿½Jï¿½ï¿½ï¿½ï¿½"), SerializeField]
    private Camera _targetCamera;

    [Header("ãƒªãƒ­ãƒ¼ãƒ‰çµ‚ã‚ã‚ŠéŸ³"), SerializeField]
    private AudioSource relordstart;
    [Header("ãƒªãƒ­ãƒ¼ãƒ‰é–‹å§‹éŸ³"), SerializeField]
    private AudioSource relordend;

    public Cinemachinecamara Vircamscript;
    public float gunguidrange;

    public float look_sensi;
    public float aimlook_length;

    private Transform _transform;
    private CharacterController _characterController;

    private Vector2 _inputMove;
    private Vector2 _look;
    bool aim=false;
    bool pastaim=false;

    bool run = false;
    bool damage = false;

    public float stmax = 1000;
    public float st = 1000;
    private bool stheal=true;
    private float sthealtimer=0f;
    public float sthealtime=1f;

    public Slider stBar;

    private float _verticalVelocity;
    private float _turnVelocity;
    private bool _isGroundedPrev;

    private Animator anim;
    [Header("ãƒªãƒ­ãƒ¼ãƒ‰ã®æœ‰åŠ¹ç„¡åŠ¹ã«ã—ã¾ã™ã€‚ç„¡åŠ¹æ™‚bUIã¯ã„ã‚‰ãªããªã‚Šã¾ã™ã€‚"), SerializeField]
    private bool relordfunction=false;
    bool endrelord=false;
    private bool walk=false;
    bool relordmode=false;
    LineRenderer itemguid;
    private GameObject[] itemlist;
    public weaponscript weapsc;
    LineRenderer gunLine;
    Ray shootRay = new Ray();
    RaycastHit shootHit;
    private GameManager gameManager;
    public bulletLvUI bUI;
    public sordLvUI sUI;
    private bool wepchange=false;
    private bool pastchange=false;
    private bool wait =false;
    private bool runwait =false;
    private bool slowwait =false;
    private bool Damagewait =false;
    void Start()
    {
        gunLine = GetComponent <LineRenderer> ();
        anim = gameObject.GetComponent<Animator>();
        gameManager = FindObjectOfType<GameManager>();
    }

    /// <summary>
    /// ï¿½Ú“ï¿½Action(PlayerInputï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚Î‚ï¿½ï¿½)
    /// </summary>
    public void OnMove(InputAction.CallbackContext context)
    {
        if(!gameManager.playerinput)return;
        _inputMove = context.ReadValue<Vector2>();
    }
    public void OnLook(InputAction.CallbackContext context)
    {
        if(!gameManager.playerinput)return;
        _look = context.ReadValue<Vector2>();
    }
    public void OnAim(InputAction.CallbackContext context)
    {
        if(!gameManager.playerinput)return;
        if (!context.performed){
            aim=false;
            
            return;
        }
        aim=true;
        
        // ï¿½ï¿½ï¿½Í’lï¿½ï¿½Ûï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½

    }
    public void OnRelord(InputAction.CallbackContext context){
        if(!gameManager.playerinput)return;
        if(relordfunction==false)return;
        if(anim.GetBool("relord"))return;
        if (!context.performed){
            relordmode=false;
            
            return;
        }
        relordmode=true;
    }
    public void OnChangeWeapon(InputAction.CallbackContext context){
        if(!gameManager.playerinput)return;
        if(anim.GetBool("relord"))return;
        if (!context.performed){
            wepchange=false;
            return;
        }
        wepchange=true;
    }

    public void OnRun(InputAction.CallbackContext context)
    {
        if(!gameManager.playerinput)return;
        if (!context.performed || st <= 30f)
        {
            run = false;

            return;
        }
        run = true;
    }

    public void P_Damage()
    {
        StartCoroutine("Wait_damage");
    }

    IEnumerator Wait_damage()
    {
        damage = true;
        anim.SetBool("itaiyou", damage);
        yield return new WaitForSeconds(1);
        damage = false;
        anim.SetBool("itaiyou", damage);
    }

    /// <summary>
    /// ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vAction(PlayerInputï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚Î‚ï¿½ï¿½)
    /// </summary>
    public void OnJump(InputAction.CallbackContext context)
    {
        if(!gameManager.playerinput)return;
        // ï¿½{ï¿½^ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½uï¿½Ô‚ï¿½ï¿½Â’ï¿½ï¿½nï¿½ï¿½ï¿½Ä‚ï¿½ï¿½éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        if (!context.performed || !_characterController.isGrounded) return;

        // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É‘ï¿½ï¿½xï¿½ï¿½^ï¿½ï¿½ï¿½ï¿½
        _verticalVelocity = _jumpSpeed;
    }

    private void Awake()
    {
        _transform = transform;
        _characterController = GetComponent<CharacterController>();

        if (_targetCamera == null)
            _targetCamera = Camera.main;
    }

    public void Dash(float stdown)
    {
        if (st <= 0) return;

        st = st - stdown;
        sthealtimer=0f;
        if (stBar != null)
        {
            stBar.value = (int)st;
        }
        if (st <= 0)
        {
            st = 0;
            run = false;
        }
    }

    public void stGain(float gain)
    {
        if (st >= stmax || st < 0||!stheal) return;

        st = st + gain;
        if (st >= stmax) st = stmax;
        if (stBar != null)
        {
            stBar.value = (int)st;
        }
    }
    private void DamageSound() //æ­©ã„ãŸæ™‚ã®Sound
        {
            if (Damagewait==false) {
            StartCoroutine("Damage_Wait_sound");
        }
        }
        IEnumerator Damage_Wait_sound()
        {
            gameManager.Sounddamage();
            Damagewait = true;
            yield return new WaitForSeconds(1.0f);
            Damagewait = false;
        }
    private void Footsound() //æ­©ã„ãŸæ™‚ã®Sound
        {
            if (wait==false) {
            StartCoroutine("Wait_sound");
        }
        }
        IEnumerator Wait_sound()
        {
            gameManager.Soundfoot();
            wait = true;
            yield return new WaitForSeconds(0.5f);
            wait = false;
        }
    private void RunFootsound() //èµ°ã£ãŸæ™‚ã®Sound
        {
            if (runwait==false) {
            StartCoroutine("Run_Wait_sound");
        }
        }
    IEnumerator Run_Wait_sound()
        {
            gameManager.Soundfoot();
            runwait = true;
            yield return new WaitForSeconds(0.2f);
            runwait = false;
        }
    private void SlowFootsound() //é…æ­©ãã®Sound
        {
            if (slowwait==false) {
            StartCoroutine("Slow_Wait_sound");
        }
        }
        IEnumerator Slow_Wait_sound()
        {
            gameManager.Soundfoot();
            slowwait = true;
            yield return new WaitForSeconds(0.8f);
            slowwait = false;
        }

    private void Update()
    {
        if(damage) //ãƒ€ãƒ¡ãƒ¼ã‚¸å—ã‘ãŸã¨ã
        {
            DamageSound();
        }
        if(anim.GetBool("Die"))return;
        if(Time.timeScale==0f)return;
        var isGrounded = _characterController.isGrounded;
        //ç€åœ°çŠ¶æ…‹ã®å‡¦ç†ã€‚ã‚¸ãƒ£ãƒ³ãƒ—ã«é–¢ä¿‚
        if (isGrounded && !_isGroundedPrev)
        {
            // ï¿½ï¿½ï¿½nï¿½ï¿½ï¿½ï¿½uï¿½Ô‚É—ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½wï¿½è‚µï¿½Ä‚ï¿½ï¿½ï¿½
            _verticalVelocity = -_initFallSpeed;
        }
        else if (!isGrounded)
        {
            // ï¿½ó’†‚É‚ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½ÍAï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Édï¿½Í‰ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½^ï¿½ï¿½ï¿½Ä—ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            _verticalVelocity -= _gravity * Time.deltaTime;

            // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½é‘¬ï¿½ï¿½ï¿½Èï¿½É‚È‚ï¿½È‚ï¿½ï¿½æ‚¤ï¿½É•â³
            if (_verticalVelocity < -_fallSpeed)
                _verticalVelocity = -_fallSpeed;
        }

        _isGroundedPrev = isGrounded;

        // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ÌŒï¿½ï¿½ï¿½ï¿½iï¿½pï¿½x[deg]ï¿½jï¿½æ“¾
        var cameraAngleY = _targetCamera.transform.eulerAngles.y;
        //ãƒœã‚¿ãƒ³å…¥åŠ›ã«ã‚ˆã‚‹æ­¦å™¨æ›¿ãˆå‡¦ç†
        bool relo=anim.GetBool("relord");
        if(relo){
        }else if(wepchange!=pastchange){
            if(!wepchange){
                pastchange=wepchange;
            }else{
                if(weapsc.changenextweapon()){
                    gameManager.Soundchangeweapon();
                    bUI.changeweapon(weapsc.weaponnumber[1]);
                    sUI.changeweapon(weapsc.weaponnumber[0]);
                }
                pastchange=wepchange;
            }
        }
        //AIMæ­¦å™¨æŒã¡æ›¿ãˆå‡¦ç†ã€€ãƒªãƒ­ãƒ¼ãƒ‰ä¸­ã¯ç„¡è¦–
        var moveVelocity = new Vector3(0,0,0);
        if(relo){
        }else if(pastaim!=aim||endrelord){
            if(aim){
                gameManager.Soundchangeweapon();
                weapsc.changeweapon(1);
                anim.SetInteger("type",1);
                gunLine.enabled = true;
            }else{
                gameManager.Soundchangeweapon();
                weapsc.changeweapon(0);
                anim.SetInteger("type",0);
                gunLine.enabled = false;
            }
            endrelord=false;
            pastaim=aim;
        }
        //ãƒªãƒ­ãƒ¼ãƒ‰å‡¦ç†
        if(relordmode==true&&weapsc.acseceweapon(1).GetComponent<WeaponStates>().relordcheck()){
            weapsc.changeweapon(1);
            relordstart.Play();
            anim.SetInteger("type",1);
            anim.SetBool("relord",true);
            gunLine.enabled = false;
            Invoke("relordsound", 2.0f);
            Invoke("Relordbullet", 2.5f);
            relordmode=false;
        }else{
            relordmode=false;
        }
        //ç§»å‹•
        weapon_speed=weapsc.weapon.GetComponent<WeaponStates>().speed;

        if (damage)
        {
            moveVelocity = new Vector3(
                _inputMove.x * weapon_speed * _speed * damage_speed,
                _verticalVelocity,
                _inputMove.y * weapon_speed * _speed * damage_speed
            );
        }
        else if (run&&_inputMove != Vector2.zero){
            Dash(250*Time.deltaTime);
            GameObject[] arbinoenemy = GameObject.FindGameObjectsWithTag("arbinoEnemy");
            foreach(GameObject obj in arbinoenemy){
                obj.GetComponent<arbinoPatrol>().sound=6;
            }
            moveVelocity = new Vector3(
                _inputMove.x *weapon_speed*run_speed* _speed,
                _verticalVelocity,
                _inputMove.y *weapon_speed*run_speed* _speed
            );
        }else{
            moveVelocity = new Vector3(
                _inputMove.x * weapon_speed*_speed,
                _verticalVelocity,
                _inputMove.y * weapon_speed*_speed
            );
        }

        moveVelocity = Quaternion.Euler(0, cameraAngleY, 0) * moveVelocity;

        // ï¿½ï¿½ï¿½İƒtï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ÌˆÚ“ï¿½ï¿½Ê‚ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½vï¿½Z
        var moveDelta = moveVelocity * Time.deltaTime;

        // CharacterControllerï¿½ÉˆÚ“ï¿½ï¿½Ê‚ï¿½ï¿½wï¿½è‚µï¿½Aï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ğ“®‚ï¿½ï¿½ï¿½
        _characterController.Move(moveDelta);
        //linelenderer(äºˆæ¸¬å°„ç·š)
        if(aim){
            shootRay.origin = transform.position;
            shootRay.direction = transform.forward;
            gunLine.SetPosition (0, transform.position);
            int shootableMask = LayerMask.GetMask ("enemy");
            if(Physics.Raycast (shootRay, out shootHit, gunguidrange, shootableMask))
            {
                gunLine.SetPosition (1, shootHit.point);
            }
            else
            {
                gunLine.SetPosition (1, shootRay.origin + shootRay.direction * gunguidrange);
            }
        }
        //ç§»å‹•ä¸­ä½•ã‚’ã™ã‚‹ã‹
        if(_inputMove != Vector2.zero)
        {
            if(aim)
            {
                SlowFootsound();
            }
            else if(run)
            {
                RunFootsound();
            }
            else
            {
                Footsound();
            }
            walk = true;
            anim.SetBool("run", run);
            anim.SetBool("walk", walk);
            guidupdate();   //ç·‘ã®ã‚„ã˜ã‚‹ã—æ›´æ–°
            if(!run)
            {
                sthealtimer+=Time.deltaTime;
                //print($"velocity = {_inputMove}");
                if(sthealtimer<sthealtime){
                    stheal=false;
                }else{
                    stheal=true;
                }
                stGain(30*Time.deltaTime);
            }
        }
        else if(_inputMove == Vector2.zero)
        {
            sthealtimer+=Time.deltaTime*2;
            if(sthealtimer<sthealtime){
                    stheal=false;
            }else{
                stheal=true;
            }
            walk = false;
            //print($"velocity = stop");
            anim.SetBool("walk", walk);
            stGain(100*Time.deltaTime);
        }
        
        if(!aim){
            Vircamscript.visionlengthX=0;
            Vircamscript.visionlengthZ=0;
            if (_look != Vector2.zero)
            {
                Vector2 A=new Vector2(_look.x,_look.y);
                A=A.normalized;
                if(_look.x/A.x<=1){
                    Vircamscript.visionlengthX=aimlook_length*_look.x/A.x;
                    Vircamscript.visionlengthZ=aimlook_length*_look.x/A.x;
                }else{
                    Vircamscript.visionlengthX=aimlook_length;
                    Vircamscript.visionlengthZ=aimlook_length;
                }
                // ï¿½Ú“ï¿½ï¿½ï¿½ï¿½Í‚ï¿½ï¿½ï¿½ï¿½ï¿½ê‡ï¿½ÍAï¿½Uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½

                // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Í‚ï¿½ï¿½ï¿½yï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì–Ú•Wï¿½pï¿½x[deg]ï¿½ï¿½ï¿½vï¿½Z
                var targetAngleY = -Mathf.Atan2(_look.y, _look.x)
                    * Mathf.Rad2Deg + 90;
                // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ÌŠpï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½pï¿½xï¿½ï¿½â³
                targetAngleY += cameraAngleY;

                // ï¿½Cï¿½[ï¿½Wï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½È‚ï¿½ï¿½çŸï¿½Ì‰ï¿½]ï¿½pï¿½x[deg]ï¿½ï¿½ï¿½vï¿½Z
                var angleY = Mathf.SmoothDampAngle(
                    _transform.eulerAngles.y,
                    targetAngleY,
                    ref _turnVelocity,
                    0.1f
                );

                // ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ì‰ï¿½]ï¿½ï¿½ï¿½Xï¿½V
                _transform.rotation = Quaternion.Euler(0, angleY, 0);
            }else if (_inputMove != Vector2.zero)
            {
                // ï¿½Ú“ï¿½ï¿½ï¿½ï¿½Í‚ï¿½ï¿½ï¿½ï¿½ï¿½ê‡ï¿½ÍAï¿½Uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½

                // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Í‚ï¿½ï¿½ï¿½yï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì–Ú•Wï¿½pï¿½x[deg]ï¿½ï¿½ï¿½vï¿½Z
                var targetAngleY = -Mathf.Atan2(_inputMove.y*look_sensi, _inputMove.x*look_sensi)
                    * Mathf.Rad2Deg + 90;
                // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ÌŠpï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½pï¿½xï¿½ï¿½â³
                targetAngleY += cameraAngleY;

                // ï¿½Cï¿½[ï¿½Wï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½È‚ï¿½ï¿½çŸï¿½Ì‰ï¿½]ï¿½pï¿½x[deg]ï¿½ï¿½ï¿½vï¿½Z
                var angleY = Mathf.SmoothDampAngle(
                    _transform.eulerAngles.y,
                    targetAngleY,
                    ref _turnVelocity,
                    0.1f
                );

                // ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ì‰ï¿½]ï¿½ï¿½ï¿½Xï¿½V
                _transform.rotation = Quaternion.Euler(0, angleY, 0);
            }
        }else{
            Vircamscript.visionlengthX=aimlook_length;
            Vircamscript.visionlengthZ=aimlook_length;
            if (_look != Vector2.zero)
            {
                // ï¿½Ú“ï¿½ï¿½ï¿½ï¿½Í‚ï¿½ï¿½ï¿½ï¿½ï¿½ê‡ï¿½ÍAï¿½Uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½

                // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Í‚ï¿½ï¿½ï¿½yï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì–Ú•Wï¿½pï¿½x[deg]ï¿½ï¿½ï¿½vï¿½Z
                var targetAngleY = -Mathf.Atan2(_look.y, _look.x)
                    * Mathf.Rad2Deg + 90;
                // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ÌŠpï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½pï¿½xï¿½ï¿½â³
                targetAngleY += cameraAngleY;

                // ï¿½Cï¿½[ï¿½Wï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½È‚ï¿½ï¿½çŸï¿½Ì‰ï¿½]ï¿½pï¿½x[deg]ï¿½ï¿½ï¿½vï¿½Z
                var angleY = Mathf.SmoothDampAngle(
                    _transform.eulerAngles.y,
                    targetAngleY,
                    ref _turnVelocity,
                    0.5f
                );

                // ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ì‰ï¿½]ï¿½ï¿½ï¿½Xï¿½V
                _transform.rotation = Quaternion.Euler(0, angleY, 0);
            }
        }
    }
    //ãƒªãƒ­ãƒ¼ãƒ‰å®Œäº†é–¢æ•°
    void relordsound(){
        relordend.Play();
    }
    private void Relordbullet(){
        anim.SetInteger("type",1);
        anim.SetBool("relord",false);
        weapsc.acseceweapon(1).GetComponent<WeaponStates>().relord();
        endrelord=true;
        bUI.MesageUpdate();
    }

    //ç·‘ã®â†’ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã‚’æ›´æ–°
    private void guidupdate(){
        itemlist = GameObject.FindGameObjectsWithTag("SphereItem");
        if(itemlist.Length==0){
        }else{
            foreach(GameObject item in itemlist){
                if(!item.GetComponent<GuidLine>().guidemode)continue;
                itemguid=item.GetComponent <LineRenderer> ();
                itemguid.SetPosition (0, _transform.position);
            }
        }
        itemlist = GameObject.FindGameObjectsWithTag("BlockItem");
        if(itemlist.Length==0)return;
        foreach(GameObject item in itemlist){
            if(!item.GetComponent<GuidLine>().guidemode)continue;
            itemguid=item.GetComponent <LineRenderer> ();
            itemguid.SetPosition (0, _transform.position);
        }
    }
}