using System.Collections;
using System.Collections.Generic;
using UnityEngine;
//NavMeshAgentï¿½gï¿½ï¿½ï¿½Æ‚ï¿½ï¿½É•Kï¿½v
using UnityEngine.AI;


//ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½NavMeshAgentï¿½Rï¿½ï¿½ï¿½|ï¿½[ï¿½lï¿½ï¿½ï¿½gï¿½ï¿½İ’u
[RequireComponent(typeof(NavMeshAgent))]

public class villager_ai : MonoBehaviour
{
    public bool stopmove=false;
    public GameObject bikkuri; 
    public Transform[] points;
    [SerializeField] int destPoint = 0;
    private NavMeshAgent agent;
    Animator anim;
    //æ”»æ’ƒã®ã‚¯ãƒ¼ãƒ«ã‚¿ã‚¤ãƒ 
    public float cooltime=3;
    private float timeforcool;
    Vector3 playerPos;
    GameObject player;
    float distance;
    private float origenalspeed;
    [SerializeField] float trackingRange = 3f;
    [SerializeField] float quitRange = 5f;
    [SerializeField] float atackRange = 3f;
    //public float _sightAngle = 30f;
    [SerializeField] bool tracking = false;
    public bool attackwait=false;

    void Start()
    {
        anim = GetComponent<Animator>();
        agent = GetComponent<NavMeshAgent>();

        // autoBraking ï¿½ğ–³Œï¿½ï¿½É‚ï¿½ï¿½ï¿½ÆAï¿½Ú•Wï¿½nï¿½_ï¿½ÌŠÔ‚ï¿½ï¿½pï¿½ï¿½ï¿½Iï¿½ÉˆÚ“ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½
        //(ï¿½Â‚Ü‚ï¿½Aï¿½Gï¿½[ï¿½Wï¿½Fï¿½ï¿½ï¿½gï¿½Í–Ú•Wï¿½nï¿½_ï¿½É‹ß‚Ã‚ï¿½ï¿½Ä‚ï¿½
        // ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½)
        agent.autoBraking = false;

        GotoNextPoint();

        //ï¿½ÇÕ‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ì–ï¿½ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        player = GameObject.Find("Player");
        timeforcool=cooltime;
        origenalspeed=agent.speed;
    }


    void GotoNextPoint()
    {
        // ï¿½nï¿½_ï¿½ï¿½ï¿½È‚É‚ï¿½ï¿½İ’è‚³ï¿½ï¿½Ä‚ï¿½ï¿½È‚ï¿½ï¿½Æ‚ï¿½ï¿½É•Ô‚ï¿½ï¿½Ü‚ï¿½
        if(points.Length==0){
            agent.destination = agent.destination=transform.position;
            return;
        }

        // ï¿½Gï¿½[ï¿½Wï¿½Fï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ï¿½ï¿½İİ’è‚³ï¿½ê‚½ï¿½Ú•Wï¿½nï¿½_ï¿½Ésï¿½ï¿½ï¿½æ‚¤ï¿½Éİ’è‚µï¿½Ü‚ï¿½
        agent.destination = points[destPoint].position;

        // ï¿½zï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ÌˆÊ’uï¿½ï¿½Ú•Wï¿½nï¿½_ï¿½Éİ’è‚µï¿½A
        // ï¿½Kï¿½vï¿½È‚ï¿½Îoï¿½ï¿½ï¿½nï¿½_ï¿½É‚ï¿½ï¿½Ç‚ï¿½Ü‚ï¿½
        destPoint = (destPoint + 1) % points.Length;
    }


    void Update()
    {
        if(anim.GetBool("Z_Die")){
            agent.destination=transform.position;
            return;
        }
        timeforcool+=Time.deltaTime;
        if(stopmove){
            agent.destination=transform.position;
            return;
        }
        playerPos = player.transform.position;
        distance = Vector3.Distance(this.transform.position, playerPos);

        if (tracking)
        {
            //ï¿½ÇÕ‚Ìï¿½ï¿½AquitRangeï¿½ï¿½è‹—ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½ç’†ï¿½~
            if (distance > quitRange)
            {
                tracking = false;
            }
            /*if (distance < atackRange)
            {
                if(!attackwait)anim.SetTrigger("Z_atack");
            }*/
            //Playerï¿½ï¿½Ú•Wï¿½Æ‚ï¿½ï¿½ï¿½
            if (agent != null && agent.isActiveAndEnabled && agent.isOnNavMesh) {
            agent.destination = playerPos;
            }
        }
        else
        {
            //Playerï¿½ï¿½trackingRangeï¿½ï¿½ï¿½ß‚Ã‚ï¿½ï¿½ï¿½ï¿½ï¿½ÇÕŠJï¿½n
            if (distance < trackingRange){
                tracking = true;
                //Summonbikkuri();
            }


            // ï¿½Gï¿½[ï¿½Wï¿½Fï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ï¿½ï¿½Ú•Wï¿½nï¿½_ï¿½É‹ß‚Ã‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ï¿½A
            // ï¿½ï¿½ï¿½Ì–Ú•Wï¿½nï¿½_ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½
            if (!agent.pathPending && agent.remainingDistance < 0.5f)
                GotoNextPoint();
            //Debug.Log(agent.velocity.magnitude);
        }
        if(distance>8.0f)changespeed(2f);
        else if(distance<1.0f&&tracking){
            agent.destination=transform.position;
            //transform.LookAt(new Vector3(playerPos.x,transform.position.y,playerPos.z));
        }
        else{
            changespeed(1f);
        }
        if(agent.velocity.magnitude > 0){
            anim.SetBool("move", true);
        }else{
            anim.SetBool("move", false);
        }
        if(distance>2.0f&&tracking)return;
        //sound=0;
        GameObject[] enemy = GameObject.FindGameObjectsWithTag("Enemy");
        foreach(GameObject obj in enemy){
            float enemydistance = Vector3.Distance(this.transform.position, obj.transform.position);
            if (enemydistance < atackRange)
            {
                if(!attackwait){//æ”»æ’ƒã—ã¦ãªã„ã¨ã
                    if(timeforcool>cooltime){
                        anim.SetTrigger("Z_atack");
                        timeforcool=0f;
                        agent.destination = obj.transform.position;
                        transform.LookAt(new Vector3(obj.transform.position.x,transform.position.y,obj.transform.position.z));

                    }
                }else{//æ”»æ’ƒä¸­
                    transform.LookAt(new Vector3(obj.transform.position.x,transform.position.y,obj.transform.position.z));
                    agent.destination = obj.transform.position;
                }
            }
        }
    }
    

    void OnDrawGizmosSelected()
    {
        //trackingRangeï¿½Ì”ÍˆÍ‚ï¿½Ô‚ï¿½ï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Åï¿½ï¿½ï¿½
        Gizmos.color = Color.red;
        Gizmos.DrawWireSphere(transform.position, trackingRange);

        //quitRangeï¿½Ì”ÍˆÍ‚ï¿½Â‚ï¿½ï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Åï¿½ï¿½ï¿½
        Gizmos.color = Color.blue;
        Gizmos.DrawWireSphere(transform.position, quitRange);

        Gizmos.color = Color.green;
        Gizmos.DrawWireSphere(transform.position, atackRange);
    }
    /*void Summonbikkuri(){
        if(timeforcool<cooltime)return;
        // Cubeãƒ—ãƒ¬ãƒãƒ–ã‚’å…ƒã«ã€ã‚¤ãƒ³ã‚¹ã‚¿ãƒ³ã‚¹ã‚’ç”Ÿæˆ
        Instantiate (bikkuri, new Vector3(this.transform.position.x,this.transform.position.y+0.2f,this.transform.position.z), Quaternion.identity);
        timeforcool=0f;
    }*/
    void Stop(){
        stopmove=true;
        anim.SetBool("move",false);
        anim.SetBool("run",false);
    }
    public void completeAttack(){
        //stopmove=false;
        //changespeed(1.0f);
        //anim.SetBool("stan",false);
        attackwait=false;
    }
    void Run(float runspeed){
        anim.SetBool("run",true);
        changespeed(runspeed);
    }
    public void StartAttack(){
        //anim.SetBool("stan",true);
        attackwait=true;
    }
    void changespeed(float speed){
        agent.speed=speed*origenalspeed;
    }
}