using UnityEngine;
using UnityEngine.InputSystem;

[RequireComponent(typeof(CharacterController))]
public class PlayerControll : MonoBehaviour
{
    [Header("é€Ÿã•"), SerializeField]
    private float _speed = 3;

    [Header("ã‚¸ãƒ£ãƒ³ãƒ—ã®é€Ÿã•"), SerializeField]
    private float _jumpSpeed = 7;

    [Header("é‡åŠ›"), SerializeField]
    private float _gravity = 15;

    [Header("è½ä¸‹é€Ÿåº¦"), SerializeField]
    private float _fallSpeed = 10;

    [Header("ï¼Ÿ"), SerializeField]
    private float _initFallSpeed = 2;

    [Header("ï¼Ÿ"), SerializeField]
    private Camera _targetCamera;

    private Transform _transform;
    private CharacterController _characterController;

    private Vector2 _inputMove;
    private float _verticalVelocity;
    private float _turnVelocity;
    private bool _isGroundedPrev;

    /// <summary>
    /// ï¿½Ú“ï¿½Action(PlayerInputï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚Î‚ï¿½ï¿½)
    /// </summary>
    public void OnMove(InputAction.CallbackContext context)
    {
        // ï¿½ï¿½ï¿½Í’lï¿½ï¿½Ûï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
        _inputMove = context.ReadValue<Vector2>();
    }

    /// <summary>
    /// ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vAction(PlayerInputï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚Î‚ï¿½ï¿½)
    /// </summary>
    public void OnJump(InputAction.CallbackContext context)
    {
        // ï¿½{ï¿½^ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½uï¿½Ô‚ï¿½ï¿½Â’ï¿½ï¿½nï¿½ï¿½ï¿½Ä‚ï¿½ï¿½éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        if (!context.performed || !_characterController.isGrounded) return;

        // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É‘ï¿½ï¿½xï¿½ï¿½^ï¿½ï¿½ï¿½ï¿½
        _verticalVelocity = _jumpSpeed;
    }

    private void Awake()
    {
        _transform = transform;
        _characterController = GetComponent<CharacterController>();

        if (_targetCamera == null)
            _targetCamera = Camera.main;
    }

    private void Update()
    {
        var isGrounded = _characterController.isGrounded;

        if (isGrounded && !_isGroundedPrev)
        {
            // ï¿½ï¿½ï¿½nï¿½ï¿½ï¿½ï¿½uï¿½Ô‚É—ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½wï¿½è‚µï¿½Ä‚ï¿½ï¿½ï¿½
            _verticalVelocity = -_initFallSpeed;
        }
        else if (!isGrounded)
        {
            // ï¿½ó’†‚É‚ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½ÍAï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Édï¿½Í‰ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½^ï¿½ï¿½ï¿½Ä—ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            _verticalVelocity -= _gravity * Time.deltaTime;

            // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½é‘¬ï¿½ï¿½ï¿½Èï¿½É‚È‚ï¿½È‚ï¿½ï¿½æ‚¤ï¿½É•â³
            if (_verticalVelocity < -_fallSpeed)
                _verticalVelocity = -_fallSpeed;
        }

        _isGroundedPrev = isGrounded;

        // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ÌŒï¿½ï¿½ï¿½ï¿½iï¿½pï¿½x[deg]ï¿½jï¿½æ“¾
        var cameraAngleY = _targetCamera.transform.eulerAngles.y;

        // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Í‚Æ‰ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½İ‘ï¿½ï¿½xï¿½ï¿½ï¿½vï¿½Z
        var moveVelocity = new Vector3(
            _inputMove.x * _speed,
            _verticalVelocity,
            _inputMove.y * _speed
        );
        // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ÌŠpï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ú“ï¿½ï¿½Ê‚ï¿½ï¿½ï¿½]
        moveVelocity = Quaternion.Euler(0, cameraAngleY, 0) * moveVelocity;

        // ï¿½ï¿½ï¿½İƒtï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ÌˆÚ“ï¿½ï¿½Ê‚ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½vï¿½Z
        var moveDelta = moveVelocity * Time.deltaTime;

        // CharacterControllerï¿½ÉˆÚ“ï¿½ï¿½Ê‚ï¿½ï¿½wï¿½è‚µï¿½Aï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ğ“®‚ï¿½ï¿½ï¿½
        _characterController.Move(moveDelta);

        if (_inputMove != Vector2.zero)
        {
            // ï¿½Ú“ï¿½ï¿½ï¿½ï¿½Í‚ï¿½ï¿½ï¿½ï¿½ï¿½ê‡ï¿½ÍAï¿½Uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½

            // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Í‚ï¿½ï¿½ï¿½yï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì–Ú•Wï¿½pï¿½x[deg]ï¿½ï¿½ï¿½vï¿½Z
            var targetAngleY = -Mathf.Atan2(_inputMove.y, _inputMove.x)
                * Mathf.Rad2Deg + 90;
            // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ÌŠpï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½pï¿½xï¿½ï¿½â³
            targetAngleY += cameraAngleY;

            // ï¿½Cï¿½[ï¿½Wï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½È‚ï¿½ï¿½çŸï¿½Ì‰ï¿½]ï¿½pï¿½x[deg]ï¿½ï¿½ï¿½vï¿½Z
            var angleY = Mathf.SmoothDampAngle(
                _transform.eulerAngles.y,
                targetAngleY,
                ref _turnVelocity,
                0.1f
            );

            // ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ì‰ï¿½]ï¿½ï¿½ï¿½Xï¿½V
            _transform.rotation = Quaternion.Euler(0, angleY, 0);
        }
    }
}
